import type { Metadata } from 'next'
import { PageShell, Section } from '@/components/common/page-shell'
import { SITE } from '@/lib/constants'

export const metadata: Metadata = {
  title: 'Privacy Policy',
  description: `How ${SITE.name} collects, uses, and protects your personal data.`,
  alternates: { canonical: '/privacy' },
  openGraph: { title: `Privacy Policy · ${SITE.name}`, url: '/privacy' },
}

export default function PrivacyPage() {
  return (
    <PageShell
      eyebrow="Legal"
      title="Privacy Policy"
      intro={`This policy explains what personal data ${SITE.name} collects, why we collect it, and the choices you have. Last updated: June 2026.`}
    >
      <Section title="Data we collect">
        <p><strong className="text-foreground">Account data.</strong> When you register we store your name, email address, and — if you sign in with Google — the basic profile information Google shares (name, email, avatar). You may add a phone number, WhatsApp number, and bio to your profile.</p>
        <p><strong className="text-foreground">Listing data.</strong> Property details, photos, and location information you submit when posting a listing. Listings are public by design.</p>
        <p><strong className="text-foreground">Activity data.</strong> Properties you save, inquiries you send (including your name and contact details, which are shared with the listing's seller), and aggregate listing statistics such as view counts.</p>
        <p><strong className="text-foreground">Technical data.</strong> Standard logs (IP address, browser type, pages visited) generated by our hosting providers for security and reliability.</p>
      </Section>
      <Section title="How we use it">
        <p>To operate the marketplace: showing your listings to buyers, delivering your inquiries to sellers, syncing your saved properties across devices, and providing sellers with analytics about their own listings. We also use data to prevent spam and abuse, and to improve the product.</p>
        <p>We do <strong className="text-foreground">not</strong> sell your personal data, and we don't show third-party advertising.</p>
      </Section>
      <Section title="Where your data lives">
        <p>Data is stored with Supabase (database, authentication, and file storage) and the site is served via Vercel. Both apply industry-standard encryption in transit and at rest. Authentication with Google is handled by Google's OAuth service; we never see your Google password.</p>
      </Section>
      <Section title="What others can see">
        <p>Your listings, including photos and the general location you provide, are public. Your name and the contact details you choose to add to a listing are visible to interested buyers. When you send an inquiry, the seller receives the name, contact details, and message you submit.</p>
      </Section>
      <Section title="Your choices">
        <p>You can edit your profile and delete your listings at any time from the dashboard. To delete your account and associated personal data, contact us at <a className="text-primary hover:underline" href="mailto:hello@estata.lk">hello@estata.lk</a> and we'll process the request promptly.</p>
      </Section>
      <Section title="Cookies">
        <p>We use only essential cookies — primarily the session cookie that keeps you signed in. No third-party advertising or cross-site tracking cookies are set.</p>
      </Section>
      <Section title="Changes & contact">
        <p>If this policy changes materially, we'll update the date above and note it on the site. Questions? Reach us at <a className="text-primary hover:underline" href="mailto:hello@estata.lk">hello@estata.lk</a>.</p>
      </Section>
    </PageShell>
  )
}
